#
#   Copyright (c) 2014-2017 CASM Organization https://casm-lang.org
#   All rights reserved.
#
#   Developed by: Philipp Paulweber
#                 Emmanuel Pescosta
#                 https://github.com/casm-lang/casm
#
#   This file is part of casm.
#
#   casm is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   casm is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with casm. If not, see <http://www.gnu.org/licenses/>.
#

sudo: required

language: cpp

services:
  - docker

git:
  submodules: false

matrix:
  include:
    - os:  linux
      env: IMAGE="ppaulweber/docker-cpp:base" BUILD="debug"    ENV_CC="clang" ENV_CXX="clang++"
    - os:  linux
      env: IMAGE="ppaulweber/docker-cpp:base" BUILD="release"  ENV_CC="clang" ENV_CXX="clang++"

    - os:  linux
      env: IMAGE="ppaulweber/docker-cpp:base" BUILD="debug"    ENV_CC="gcc"   ENV_CXX="g++"
    - os:  linux
      env: IMAGE="ppaulweber/docker-cpp:base" BUILD="release"  ENV_CC="gcc"   ENV_CXX="g++"

  allow_failures:
    - os:  linux
      env: IMAGE="ppaulweber/docker-cpp" BUILD="debug"    ENV_CC="clang" ENV_CXX="clang++"
    - os:  linux
      env: IMAGE="ppaulweber/docker-cpp" BUILD="sanitize" ENV_CC="clang" ENV_CXX="clang++"
    - os:  linux
      env: IMAGE="ppaulweber/docker-cpp" BUILD="release"  ENV_CC="clang" ENV_CXX="clang++"

    - os:  linux
      env: IMAGE="ppaulweber/docker-cpp" BUILD="debug"    ENV_CC="gcc" ENV_CXX="g++"
    - os:  linux
      env: IMAGE="ppaulweber/docker-cpp" BUILD="sanitize" ENV_CC="gcc" ENV_CXX="g++"
    - os:  linux
      env: IMAGE="ppaulweber/docker-cpp" BUILD="release"  ENV_CC="gcc" ENV_CXX="g++"

    - os:        osx
      osx_image: xcode8
      compiler:  clang

    - os:        osx
      osx_image: xcode8
      compiler:  gcc

before_install:
  - git submodule update --init --remote
  - docker pull ${IMAGE}
  - docker run -itd --name build -v $(pwd):/repo ${IMAGE} bash

install:
  - docker exec build uname      -a
  - docker exec build make       --version
  - docker exec build cmake      --version
  - docker exec build ld         --version
  - docker exec build ${ENV_CC}  --version
  - docker exec build ${ENV_CXX} --version

script:
  - docker exec build make -C /repo ${BUILD}
  - docker exec build make -C /repo ${BUILD}-test
  - docker exec build make -C /repo ${BUILD}-benchmark

after_success:
  - docker exec build make -C /repo ${BUILD}-analyze
